#!/usr/bin/env bash
# Install Nginx package and dependencies

apt-get update
apt-get install -y nginx

echo "Holberton School for the win!" > /var/www/html/index.html
sed -i 's/80 default_server;/80 default_server;\n       rewrite ^\/?$ \/index.html permanent;/' /etc/nginx/sites-available/default
systemctl restart nginx
 