#!/usr/bin/env bash
# Install Nginx package and dependencies

sudo apt-get update
sudo apt-get install -y nginx

sudo sed -i 's/# listen 80/listen 80/' /etc/nginx/sites-available/default

sudo echo "Holberton School for the win!" > /var/www/html/index.html
sudo service nginx restart
